[versions]
commons-codec = "1.18.0"
commons-lang3 = "3.17.0"
hamcrest = "3.0"
junit5 = "5.12.2"
kotlin-jvm = "2.1.21"
python-plugin = "3.1.1"
sonarqube-plugin = "6.2.0.5505"
struts2 = "7.0.3"

[libraries]
commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commons-codec" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }
struts2-core = { group = "org.apache.struts", name = "struts2-core", version.ref = "struts2" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
python-plugin = { id = "com.pswidersk.python-plugin", version.ref = "python-plugin" }
sonarqube-plugin = { id = "org.sonarqube", version.ref = "sonarqube-plugin" }
